[2025-04-08T05:09:13.707+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T05:09:13.728+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Download_Stock_Price.save_to_database manual__2025-04-08T05:09:03.797411+00:00 [queued]>
[2025-04-08T05:09:13.738+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Download_Stock_Price.save_to_database manual__2025-04-08T05:09:03.797411+00:00 [queued]>
[2025-04-08T05:09:13.739+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-08T05:09:13.754+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): save_to_database> on 2025-04-08 05:09:03.797411+00:00
[2025-04-08T05:09:13.760+0000] {standard_task_runner.py:72} INFO - Started process 17040 to run task
[2025-04-08T05:09:13.764+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Download_Stock_Price', 'save_to_database', 'manual__2025-04-08T05:09:03.797411+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/download_stock_price.py', '--cfg-path', '/tmp/tmpmnf7309n']
[2025-04-08T05:09:13.765+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask save_to_database
[2025-04-08T05:09:13.826+0000] {task_command.py:467} INFO - Running <TaskInstance: Download_Stock_Price.save_to_database manual__2025-04-08T05:09:03.797411+00:00 [running]> on host instance-20250307-222520.us-central1-a.c.esoteric-realm-448604-v0.internal
[2025-04-08T05:09:13.918+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Download_Stock_Price' AIRFLOW_CTX_TASK_ID='save_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T05:09:03.797411+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T05:09:03.797411+00:00'
[2025-04-08T05:09:13.919+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-08T05:09:13.920+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-08T05:09:13.920+0000] {logging_mixin.py:190} INFO - Current task name:save_to_database state:running start_date:2025-04-08 05:09:13.728687+00:00
[2025-04-08T05:09:13.921+0000] {logging_mixin.py:190} INFO - Dag name:Download_Stock_Price and current dag run status:running
[2025-04-08T05:09:13.921+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T05:09:13.936+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/workspace/airflow/dags/download_stock_price.py", line 106, in save_to_mysql_stage
    mydb = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "airflow"

[2025-04-08T05:09:13.952+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-08T05:09:13.953+0000] {logging_mixin.py:190} INFO - Task start:2025-04-08 05:09:13.728687+00:00 end:2025-04-08 05:09:13.952336+00:00 duration:0.223649
[2025-04-08T05:09:13.953+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): save_to_database> dag:<DAG: Download_Stock_Price> dagrun:<DagRun Download_Stock_Price @ 2025-04-08 05:09:03.797411+00:00: manual__2025-04-08T05:09:03.797411+00:00, state:running, queued_at: 2025-04-08 05:09:03.841195+00:00. externally triggered: True>
[2025-04-08T05:09:13.953+0000] {logging_mixin.py:190} INFO - Failure caused by connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "airflow"
[2025-04-08T05:09:13.954+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=Download_Stock_Price, task_id=save_to_database, run_id=manual__2025-04-08T05:09:03.797411+00:00, execution_date=20250408T050903, start_date=20250408T050913, end_date=20250408T050913
[2025-04-08T05:09:13.989+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T05:09:13.990+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task save_to_database (connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "airflow"
; 17040)
Traceback (most recent call last):
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/workspace/airflow/dags/download_stock_price.py", line 106, in save_to_mysql_stage
    mydb = psycopg2.connect(
           ^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  password authentication failed for user "airflow"

[2025-04-08T05:09:14.017+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-08T05:09:14.044+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T05:09:14.046+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
