[2025-04-08T05:11:57.473+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T05:11:57.503+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Download_Stock_Price.save_to_database manual__2025-04-08T05:11:48.193947+00:00 [queued]>
[2025-04-08T05:11:57.518+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Download_Stock_Price.save_to_database manual__2025-04-08T05:11:48.193947+00:00 [queued]>
[2025-04-08T05:11:57.519+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-08T05:11:57.540+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): save_to_database> on 2025-04-08 05:11:48.193947+00:00
[2025-04-08T05:11:57.548+0000] {standard_task_runner.py:72} INFO - Started process 17719 to run task
[2025-04-08T05:11:57.554+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Download_Stock_Price', 'save_to_database', 'manual__2025-04-08T05:11:48.193947+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/download_stock_price.py', '--cfg-path', '/tmp/tmps4z5kjjg']
[2025-04-08T05:11:57.556+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask save_to_database
[2025-04-08T05:11:57.632+0000] {task_command.py:467} INFO - Running <TaskInstance: Download_Stock_Price.save_to_database manual__2025-04-08T05:11:48.193947+00:00 [running]> on host instance-20250307-222520.us-central1-a.c.esoteric-realm-448604-v0.internal
[2025-04-08T05:11:57.753+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Download_Stock_Price' AIRFLOW_CTX_TASK_ID='save_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T05:11:48.193947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T05:11:48.193947+00:00'
[2025-04-08T05:11:57.756+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-08T05:11:57.757+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-08T05:11:57.757+0000] {logging_mixin.py:190} INFO - Current task name:save_to_database state:running start_date:2025-04-08 05:11:57.504591+00:00
[2025-04-08T05:11:57.758+0000] {logging_mixin.py:190} INFO - Dag name:Download_Stock_Price and current dag run status:running
[2025-04-08T05:11:57.759+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T05:11:57.778+0000] {logging_mixin.py:190} INFO - IBM length=21   ['IBM', '2025-03-11 00:00:00-04:00', '255.99000549316406', '256.70001220703125', '245.86000061035156', '248.9499969482422']
[2025-04-08T05:11:57.787+0000] {logging_mixin.py:190} INFO - 21 record inserted.
[2025-04-08T05:11:57.787+0000] {logging_mixin.py:190} INFO - GE length=21   ['GE', '2025-03-11 00:00:00-04:00', '189.92999267578125', '193.67999267578125', '188.32000732421875', '191.72000122070312']
[2025-04-08T05:11:57.796+0000] {logging_mixin.py:190} INFO - 21 record inserted.
[2025-04-08T05:11:57.797+0000] {logging_mixin.py:190} INFO - AAPL length=21   ['AAPL', '2025-03-11 00:00:00-04:00', '223.80999755859375', '225.83999633789062', '217.4499969482422', '220.83999633789062']
[2025-04-08T05:11:57.806+0000] {logging_mixin.py:190} INFO - 21 record inserted.
[2025-04-08T05:11:57.807+0000] {logging_mixin.py:190} INFO - MSFT length=21   ['MSFT', '2025-03-11 00:00:00-04:00', '379.0', '386.0', '376.9100036621094', '380.45001220703125']
[2025-04-08T05:11:57.816+0000] {logging_mixin.py:190} INFO - 21 record inserted.
[2025-04-08T05:11:57.817+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/workspace/airflow/dags/download_stock_price.py", line 117, in save_to_mysql_stage
    print(f"{ticker} length={len(val)}   {val[1]}")
                                          ~~~^^^
IndexError: list index out of range
[2025-04-08T05:11:57.837+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-08T05:11:57.837+0000] {logging_mixin.py:190} INFO - Task start:2025-04-08 05:11:57.504591+00:00 end:2025-04-08 05:11:57.836466+00:00 duration:0.331875
[2025-04-08T05:11:57.838+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): save_to_database> dag:<DAG: Download_Stock_Price> dagrun:<DagRun Download_Stock_Price @ 2025-04-08 05:11:48.193947+00:00: manual__2025-04-08T05:11:48.193947+00:00, state:running, queued_at: 2025-04-08 05:11:48.211477+00:00. externally triggered: True>
[2025-04-08T05:11:57.838+0000] {logging_mixin.py:190} INFO - Failure caused by list index out of range
[2025-04-08T05:11:57.839+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=Download_Stock_Price, task_id=save_to_database, run_id=manual__2025-04-08T05:11:48.193947+00:00, execution_date=20250408T051148, start_date=20250408T051157, end_date=20250408T051157
[2025-04-08T05:11:57.882+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T05:11:57.883+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task save_to_database (list index out of range; 17719)
Traceback (most recent call last):
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gloria/workspace/airflow/dags/download_stock_price.py", line 117, in save_to_mysql_stage
    print(f"{ticker} length={len(val)}   {val[1]}")
                                          ~~~^^^
IndexError: list index out of range
[2025-04-08T05:11:57.930+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-08T05:11:57.956+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T05:11:57.958+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
